# yaml有层次,可以继承的配置文件格式
# key:
# 缩进key:  -> key.key
server:
  port: 8088
  servlet:
    context-path: /book

# 自定义配置（yaml格式）
xiaoming:
  user:
    gfs:
      - a
      - b
      - c

# 激活外部配置
spring:
  profiles:
    active: test,dev,druid
  # 禁用数据库初始化脚本，避免自动配置H2驱动
  sql:
    init:
      mode: never